

let cardData = [
  {
    title: 'Nokia G300',
    price: 50399,
    category: 'Smartphones',
    type: "Nokia",
    imgLink: 'https://images.ctfassets.net/wcfotm6rrl7u/bVyZldY7SkOMbLRp63qyW/e1372fdfa65ac7638c8d33f48b961db8/nokia-G300-grey-front_back-us.png?h=600&fm=webp',
    description: "The versatile 16 MP triple-lens camera captures stunning detailed photos, beautiful portraits, epic landscapes and motion shots. Capture your kid’s first basketball game, the dog doing tricks, or simple moments to remember with 1080p at 60fps for smoother motion shots. And with image stabilization, OZO spatial audio and wind noise cancellation, your memories are preserved in excellent detail.",
    status: 'In Stock',
  },
  {
    title: 'Nokia G50',
    price: 52399,
    category: 'Smartphones',
    type: "Nokia",
    imgLink: 'https://images.ctfassets.net/wcfotm6rrl7u/76fSPXUoCY4M6TVXVK1ofr/582329d4c4bdb6e79b9a9fbdf1f5e371/nokia-G50-ocean_blue-front_back-int.png?h=600&fm=webp',
    description: "A better-quality phone is better for you, better for your pocket and better for the planet. That’s the idea behind Nokia G50, a future-proof smartphone that’s great for today and ready for tomorrow. It’s 5G-ready¹ thanks to the Qualcomm® Snapdragon™ 480 5G Mobile Platform at its core. Nokia G50 is also equipped with a battery that can last for days, a 48 MP triple camera supported by AI and image stabilisation, Nordic reliability and build quality and the very latest Android™ 11, with 2 years of OS updates and 3 years of monthly security updates.",
    status: 'In Stock',
  },
  {
    title: 'Nokia XR20',
    price: 95949,
    category: 'Smartphones',
    type: "Nokia",
    imgLink: 'https://images.ctfassets.net/wcfotm6rrl7u/2uRIDMY0mMHEtKXnTHid3B/9e5dfaccc1999c4ae5a7c8bfaccf728f/nokia-XR20-ultrablue-front_back-int.png?h=600&fm=webp',
    description: "Nokia XR20 is designed for the long run. A phone that can stand up to anything life throws at it – and look great doing it. With an ultra-solid case and the toughest display glass we could find, it’s scratch-resistant, drop-resistant, temperature-resistant, water-resistant and kid-and-pet-resistant. It also comes with up to 3 years of OS upgrades and 4 years of monthly security updates, so your phone will be up to date into 2025. And because you’ll be using it longer, it’s better for the environment.",
    status: 'In Stock',
  },
  {
    title: 'Nokia 2V Tella',
    price: 19949,
    category: 'Smartphones',
    type: "Nokia",
    imgLink: 'https://images.ctfassets.net/wcfotm6rrl7u/2kIyv0F1jLGUkCPvJR22Zt/b6d0514c259abe85f0dae77dd14a3ed9/nokia-2_V_Tella-blue-front_back-us.png?h=600&fm=webp',
    description: "Get doubly creative with the dual rear 8 MP + 2 MP cameras. Always get the best picture with recommended shot – it captures multiple images before and after the shutter is pressed, then suggests the one to keep. Plus, take standout photos – even after dark – in Portrait mode.",
    status: 'In Stock',
  },


  {
    title: 'iPhone 13 Pro',
    price: 322999,
    category: 'Smartphones',
    type: "iPhone",
    imgLink: 'https://www.apple.com/v/iphone-13-pro/c/images/overview/design/water_resistant__gnhxpuloslay_medium.jpg',
    description: "With its redesigned lens and powerful autofocus system, the new Ultra Wide camera can focus at just 2 cm — making even the smallest details seem epic. Transform a leaf into abstract art. Capture a caterpillar’s fuzz. Magnify a dewdrop. The beauty of tiny awaits.",
    status: 'In Stock',
  },
  {
    title: 'iPhone 11',
    price: 292999,
    category: 'Smartphones',
    type: "iPhone",
    imgLink: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone11-green-select-2019?wid=470&hei=556&fmt=png-alpha&.v=1566956144838',
    description: "With its redesigned lens and powerful autofocus system, the new Ultra Wide camera can focus at just 2 cm — making even the smallest details seem epic. Transform a leaf into abstract art. Capture a caterpillar’s fuzz. Magnify a dewdrop. The beauty of tiny awaits.",
    status: 'In Stock',
  },
  {
    title: 'Refurbished iPhone XS',
    price: 292599,
    category: 'Smartphones',
    type: "iPhone",
    imgLink: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/refurb-iphone-xs-max-gold?wid=572&hei=572&fmt=jpeg&qlt=95&.v=1579299533651',
    description: "Originally released September 2018 Unlocked, SIM-Free, Model A1921¹ 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with Next-generation Neural Engine Talk time (wireless) up to 25 hours Gigabit-class LTE with 4x4 MIMO and LAA 802.11ac Wi‑Fi with 2x2 MIMO Bluetooth 5.0 wireless technology NFC with reader mode Dual 12MP wide-angle and telephoto cameras 2x optical zoom; digital zoom up to 10x 4K video recording, 1080p HD video recording 7MP TrueDepth camera with Portrait mode and lighting",
    status: 'In Stock',
  },
  {
    title: 'Xiaomi Mi 9T',
    price: 92599,
    category: 'Smartphones',
    type: "Xiaomi Mi",
    imgLink: 'https://www.mega.pk/items_images/Xiaomi+Mi+9T+Mobile+6GB+RAM+128GB+Storage+Price+in+Pakistan%2C+Specifications%2C+Features%2C+Reviews_-_19437.jpg',
    description: "Xiaomi is going to launch Mi 9T, that might be the Pro version of this series. The last years launching giving us a hint that the company is following the same pattern as it did last year with 8 series. Xiaomi Mi 9T is offering many features being a flagship of the fleet. It seems that the company is looking very keen to invest more in the flagship version. The upcoming Xiaomi's Mi 9T is packed with high-end SoC, gigantic type of memory status and attractive design. This global handset will be powered by the latest chipset, Snapdragon 730. So, the new Xiaomi Mi 9T's packed with the best possible SoC available in the market. It has got a built-in GPU Adreno 640. The chipset ensures 20% better performance than any other chipset.",
    status: 'In Stock',
  },
  {
    title: 'Xiaomi Mi Note 10 Lite',
    price: 57999,
    category: 'Smartphones',
    type: "Xiaomi Mi",
    imgLink: 'https://images.priceoye.pk/xiaomi-mi-note-10-lite-pakistan-priceoye-61b3c-500x500.webp',
    description: "Xiaomi is going to launch Mi 9T, that might be the Pro version of this series. The last years launching giving us a hint that the company is following the same pattern as it did last year with 8 series. Xiaomi Mi 9T is offering many features being a flagship of the fleet. It seems that the company is looking very keen to invest more in the flagship version. The upcoming Xiaomi's Mi 9T is packed with high-end SoC, gigantic type of memory status and attractive design. This global handset will be powered by the latest chipset, Snapdragon 730. So, the new Xiaomi Mi 9T's packed with the best possible SoC available in the market. It has got a built-in GPU Adreno 640. The chipset ensures 20% better performance than any other chipset.",
    status: 'In Stock',
  },
  {
    title: 'Realme X3 Super Zoom',
    price: 47999,
    category: 'Smartphones',
    type: "Redmi",
    imgLink: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2118&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Realme 7 Pro',
    price: 43899,
    category: 'Smartphones',
    type: "Redmi",
    imgLink: 'https://images.unsplash.com/photo-1535240073203-05bc5d7f1113?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=736&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Realme 6 pro',
    price: 58299,
    category: 'Smartphones',
    type: "Redmi",
    imgLink: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1227&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'Sold Out',
  },
  {
    title: 'Realme XT',
    price: 52999,
    category: 'Smartphones',
    type: "Redmi",
    imgLink: 'https://images.unsplash.com/photo-1597740985671-2a8a3b80502e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=987&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Realme 2 Pro',
    price: 67899,
    category: 'Smartphones',
    type: "Redmi",
    imgLink: 'https://images.unsplash.com/photo-1609252925148-b0f1b515e111?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Samsung Galaxy Z Fold 3',
    price: 67899,
    category: 'Smartphones',
    type: "Samsung",
    imgLink: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1926&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'Sold Out',
  },
  {
    title: 'Samsung Galaxy Z Fold 2',
    price: 67899,
    category: 'Smartphones',
    type: "Samsung",
    imgLink: 'https://images.unsplash.com/photo-1597740985671-2a8a3b80502e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Samsung Galaxy S21 Ultra',
    price: 67899,
    category: 'Smartphones',
    type: "Samsung",
    imgLink: 'https://images.unsplash.com/photo-1551721434-8b94ddff0e6d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1965&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Black Samsung Galaxy Tab',
    price: 67899,
    category: 'Smartphones',
    type: "Samsung",
    imgLink: 'https://images.unsplash.com/photo-1609252924198-30b8cb324d2b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1587&q=80',
    description: "Black Samsung Galaxy Tab time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Samsung Galaxy Z Flip',
    price: 67899,
    category: 'Smartphones',
    type: "Samsung",
    imgLink: 'https://images.unsplash.com/photo-1592813630413-1124aa567638?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1485&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },


  // Gaming
  {
    title: 'Sony PS4 game controller',
    price: 67899,
    category: 'Gaming',
    type: "PlayStation Controllers",
    imgLink: 'https://images.unsplash.com/photo-1567027757540-7b572280fa22?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=687&q=80',
    description: "Black Sony PS4 game controller this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'white PS4 dualshock 4',
    price: 67899,
    category: 'Gaming',
    type: "PlayStation Controllers",
    imgLink: 'https://images.unsplash.com/photo-1535043205849-513fe27db33e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2080&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Sony PS3 controller',
    price: 67899,
    category: 'Gaming',
    type: "PlayStation Controllers",
    imgLink: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2147&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'black wireless game controller',
    price: 67899,
    category: 'Gaming',
    type: "PlayStation Controllers",
    imgLink: 'https://images.unsplash.com/photo-1492044715545-15ddedd84e5e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Black VR Controller',
    price: 67899,
    category: 'Gaming',
    type: "PlayStation Controllers",
    imgLink: 'https://images.unsplash.com/photo-1529970177251-65248cff153a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },



  {
    title: 'PlayStation 4 Pro',
    price: 67899,
    category: 'Gaming',
    type: "PlayStation Console",
    imgLink: 'https://m.media-amazon.com/images/I/6118ctEjpoL._AC_SL1500_.jpg',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'PlayStation 4',
    price: 67899,
    category: 'Gaming',
    type: "PlayStation Console",
    imgLink: 'https://gmedia.playstation.com/is/image/SIEPDC/ps4-slim-image-block-01-en-24jul20?$1600px--t$',
    description: "PlayStation 4 with 1TB storage this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },

  {
    title: 'PlayStation 4 Pro',
    price: 67899,
    category: 'Gaming',
    type: "PlayStation Console",
    imgLink: 'https://gmedia.playstation.com/is/image/SIEPDC/ps4-pro-image-block-01-en-24jul20?$1600px--t$',
    description: "4K-gaming and entertainment with vibrant HDR is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'SONY PS4 Pro',
    price: 67899,
    category: 'Gaming',
    type: "PlayStation Console",
    imgLink: 'https://rocket.pk/media/catalog/product/cache/74c1057f7991b4edb2bc7bdaa94de933/6/1/61_j77gbrpl._sl1470_.jpg',
    description: "SONY PS4 Pro - CUH-7116BB02Y PS4 PRO 1TB / Whitebring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },


  // Xbox Consoles
  {
    title: 'Xbox Console',
    price: 67899,
    category: 'Gaming',
    type: "Xbox Consoles",
    imgLink: 'https://images.unsplash.com/photo-1536704689578-8fff53d4dfd7?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1974&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Xbox Console',
    price: 67899,
    category: 'Gaming',
    type: "Xbox Consoles",
    imgLink: 'https://compass-ssl.xbox.com/assets/80/d0/80d0e9ad-1e75-4fe0-9239-115d13da251a.jpg?n=XBX_HMC_D_Landing.jpg',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Xbox Console',
    price: 67899,
    category: 'Gaming',
    type: "Xbox Consoles",
    imgLink: 'https://cdn.geekwire.com/wp-content/uploads/2020/09/Still-Image_Console-Family_2_Back-to-Back_Consoles-Controllers-630x496.png',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Xbox Console',
    price: 67899,
    category: 'Gaming',
    type: "Xbox Consoles",
    imgLink: 'https://images.unsplash.com/photo-1621259181233-aa03cf592ea7?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1629&q=80',
    description: "Xbox Consoles this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },




  // Cameras & Drones
  {
    title: 'Black DSLR camera on black tripod',
    price: 67899,
    category: 'Cameras & Drones',
    type: "Video Camera",
    imgLink: 'https://images.unsplash.com/photo-1589976585164-f41085680533?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1974&q=80',
    description: "Black DSLR camera on black tripod is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Black camera with stand',
    price: 67899,
    category: 'Cameras & Drones',
    type: "Video Camera",
    imgLink: 'https://images.unsplash.com/photo-1568605595399-83af71a09395?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80',
    description: "Black camera with stand time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Black DSLR camera',
    price: 67899,
    category: 'Cameras & Drones',
    type: "Video Camera",
    imgLink: 'https://images.unsplash.com/photo-1585438814927-7a5bb5465b6f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2127&q=80',
    description: "Black DSLR camera but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Black Canon EOS DSLR',
    price: 67899,
    category: 'Cameras & Drones',
    type: "Video Camera",
    imgLink: 'https://images.unsplash.com/photo-1547250090-ced82d12986c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80',
    description: "black Canon EOS DSLR camera with stand is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },

  {
    title: 'DJI Mavic Pro quadcopter',
    price: 67899,
    category: 'Cameras & Drones',
    type: "Drones",
    imgLink: 'https://images.unsplash.com/photo-1539213465191-6046fe072ade?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1974&q=80',
    description: "Black DJI Mavic Pro quadcopter new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Black and gray Drone',
    price: 67899,
    category: 'Cameras & Drones',
    type: "Drones",
    imgLink: 'https://images.unsplash.com/photo-1617165556464-ba1248d57001?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2127&q=80',
    description: "Black and gray Drone flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'DJI Phantom 3',
    price: 67899,
    category: 'Cameras & Drones',
    type: "Drones",
    imgLink: 'https://images.unsplash.com/photo-1480434945668-94be06bbd507?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1173&q=80',
    description: "white and gold DJI Phantom 3 Professional selective focus photography Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'White drone',
    price: 67899,
    category: 'Cameras & Drones',
    type: "Drones",
    imgLink: 'https://images.unsplash.com/photo-1620873630296-7822b6b28231?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2127&q=80',
    description: "white and black corded device photo – Free Film maker Image on Unsplash to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },


  {
    title: 'Canon EF lens 77mm',
    price: 67899,
    category: 'Cameras & Drones',
    type: "Camera Lens",
    imgLink: 'https://images.unsplash.com/photo-1593704212686-6d52058fb516?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2012&q=80',
    description: "Xiaomi is back with the Mi 9 but this time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Black camera lens',
    price: 67899,
    category: 'Cameras & Drones',
    type: "Camera Lens",
    imgLink: 'https://images.unsplash.com/photo-1584647854126-268e13c8bbc3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=765&q=80',
    description: "Black camera lens time this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'black Canon EF lenses',
    price: 67899,
    category: 'Cameras & Drones',
    type: "Camera Lens",
    imgLink: 'https://images.unsplash.com/photo-1551332772-66c1f79f461c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
    description: "black Canon EF lenses this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },


  // Desktops 
  {
    title: 'Dell OptiPlex 3080',
    price: 67899,
    category: 'Desktops',
    type: "Dell",
    imgLink: 'https://static.bhphoto.com/images/images500x500/dell_3hfx0_optiplex_3080_desktop_computer_1628771777_1657936.jpg',
    description: "Dell OptiPlex 3080 Small Form Factor Desktop Computer this new flagship is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Dell OptiPlex 7060',
    price: 88000,
    category: 'Desktops',
    type: "Dell",
    imgLink: 'https://myshop.pk/pub/media/catalog/product/cache/044822f421975447750ae9c7b18ed8ed/d/e/dell_optiplex_mt_desktop_7060_myshop_pk_01.jpg',
    description: "Dell OptiPlex 7060 - MT Desktop i5 - 1Y is gonna bring new things to the table and top of that list is its triple camera setup. Before that Huawei brought triple in its flagship and now Xiaomi Mi 9 is also getting ready to ride that train. Samsung took lead by introducing four camera phone not in its flagship but a mid range.",
    status: 'In Stock',
  },
  {
    title: 'Dell Optiplex 390 Desktop',
    price: 20500,
    category: 'Desktops',
    type: "Dell",
    imgLink: 'http://pointone.com.pk/wp-content/uploads/2019/12/71csr4vmizl._sx425__790d.jpg',
    description: "Dell Optiplex 390 Desktop Intel Core i7 2600 3.40GHZ 4GB DDR3 Ram 500GB SATA HDD DVD Rom Intel Q65 Express Chipset Built-in Sound, Lan",
    status: 'In Stock',
  },

  {
    title: 'HP ProDesk 600 G6',
    price: 20500,
    category: 'Desktops',
    type: "HP",
    imgLink: 'https://static.bhphoto.com/images/images1000x1000/1625140056_1645539.jpg',
    description: "HP ProDesk 600 G6 Micro-Tower Desktop Computer Take advantage of enterprise-level computing in a compact form factor with the ProDesk 600 G6 Micro-Tower Desktop Computer from HP. Featuring a 10th Gen Intel Core i5 CPU and 16GB of DDR4 RAM for responsive processing, this computer also sports a preinstalled 512GB M.2 SSD. An empty M.2 2280 slot can also be used to expand storage with a second SSD, available separately. Integrated Intel UHD Graphics 630 tackles visuals, and two DisplayPort outputs can be used to connect monitors.",
    status: 'In Stock',
  },
  {
    title: 'HP Pavilion Desktop',
    price: 55699,
    category: 'Desktops',
    type: "HP",
    imgLink: 'https://static.bhphoto.com/images/images1000x1000/1603380058_1599001.jpg',
    description: "Processing power meets connectivity with the Pavilion Desktop in natural silver from HP. Designed for everyday computing and web browsing, this desktop features a 3.6 GHz Intel Core i3-10100 quad-core CPU and 8GB of 2666 MHz DDR4 RAM. Store files using the 512GB M.2 SSD. Need more storage? Connect external drives or other wired accessories using four USB 3.2 Gen 1 Type-A ports or a Type-C port on the front panel; four USB 2.0 Type-A ports on the rear panel provide connections for wired peripherals. Can't stand clutter? Connect your wireless accessories using Bluetooth 4.2. Surf the web using a wired Gigabit Ethernet connection or Wi-Fi 5.",
    status: 'In Stock',
  },
  {
    title: 'HP ProDesk 400 G7',
    price: 20500,
    category: 'Desktops',
    type: "HP",
    imgLink: 'https://static.bhphoto.com/images/images500x500/1613504249_1623273.jpg',
    description: "HP ProDesk 400 G7 Small Form Factor Desktop Computer Built to fit in modern workspaces, the ProDesk 400 G6 Small Form Factor Desktop Computer from HP is a small, reliable, and secure system with scalable performance that can grow with your business. It is powered by a 10th Gen 3.1 GHz Intel Core i5-10500 Six-Core processor that will allow you to run multiple applications simultaneously. If you need more power, the CPU can achieve speeds up to 4.5 GHz. The 8GB of 2666 MHz DDR4 RAM helps the computer to run multiple applications simultaneously, as well as access frequently used files and programs. The current memory configuration is one 8GB module with an additional slot available for memory upgrades, making for a total of two 288-pin DIMM slots. With both slots in use, this system supports 64GB of RAM to keep up with the current demands of the latest software programs.",
    status: 'In Stock',
  },

  {
    title: 'Lenovo Mini 5 Desktop',
    price: 55000,
    category: 'Desktops',
    type: "Lenovo",
    imgLink: 'https://static.bhphoto.com/images/images1000x1000/1621946747_1640943.jpg',
    description: "Lenovo IdeaCentre Mini 5 Desktop Computer Save space in your workplace without sacrificing performance with the Lenovo IdeaCentre Mini 5 Desktop Computer. Housed in this compact design is a 2.9 GHz 10th Gen Intel Core i5 6-core processor and 8GB of 2666 MHz DDR4 RAM, allowing you to run CPU-intensive apps with ease. The 512GB M.2 NVMe PCIe SSD allows for fast boot times. Visuals are handled by integrated Intel UHD Graphics. To connect to the internet, you can use a wired connection via the Gigabit Ethernet RJ45 LAN jack or opt to go wireless with Wi-Fi 6 (802.11ax). Bluetooth 5.0 allows you to connect wirelessly to compatible accessories and peripherals. For ports, there are DisplayPort, USB Type-C, and USB Type-A.",
    status: 'In Stock',
  },
  {
    title: 'Lenovo ThinkStation P340',
    price: 20500,
    category: 'Desktops',
    type: "Lenovo",
    imgLink: 'https://static.bhphoto.com/images/images500x500/1607536809_1609622.jpg',
    description: "Lenovo ThinkStation P340 Small Form Factor Desktop Computer Streamline your business and increase productivity with the ThinkStation P340 Small Form Factor Desktop Computer from Lenovo. This compact design houses a 10th generation 2.9 GHz Intel Core i7 eight-core CPU, 16GB 2933 MHz DDR4 RAM, and 512GB M.2 PCIe",
    status: 'In Stock',
  },
  {
    title: 'Lenovo ThinkStation P340',
    price: 20500,
    category: 'Desktops',
    type: "Lenovo",
    imgLink: 'https://static.bhphoto.com/images/images1000x1000/1600693567_1593567.jpg',
    description: "Lenovo ThinkStation P340 Tiny Desktop ComputerEnhance the productivity of your home or office while maximizing your desktop space with the Lenovo ThinkStation P340 Tiny Desktop Computer. This small form-factor desktop system is packed with power, featuring a 10th generation 3.1 GHz Intel Core i5-10500 six-core processor with 16GB of DDR4-2933 memory and a fast 1TB M.2 PCIe NVMe solid-state drive to quickly load and multitask demanding applications. You can upgrade the system's memory to by installing a 260-pin SO-DIMM into the available slot to help increase the computer's efficiency when handling large projects. The system supports up to 64GB of RAM. A second M.2 slot is also available for additional storage. The integrated Intel UHD 630 graphics is designed to efficiently run a variety of applications with high detail. Up to three monitors can be connected across the computerâ¿¿s HDMI and DisplayPort outputs for enhanced viewing and multitasking efficiency.",
    status: 'In Stock',
  },


  // Mobile Accessories
  {
    title: 'iPhone all models',
    price: 20500,
    category: 'Mobile Accessories',
    type: "Phone Casses",
    imgLink: 'https://cdn.shopify.com/s/files/1/1945/3873/products/ScreenShot2020-07-09at12.44.03PM_741x739.png?v=1629979598',
    description: "iPhone all models fluorescent Shockproof transparent soft case 1 pcs. We offer 7-Days no question asked Replacement policy. 1-3 working Days Delivery Time all over Pakistan",
    status: 'In Stock',
  },
  {
    title: 'iPhone Leather Case',
    price: 12999,
    category: 'Mobile Accessories',
    type: "Phone Casses",
    imgLink: 'https://cdn.shopify.com/s/files/1/1945/3873/products/555_a17a4e02-6be3-4a7d-9611-41f5ac6d2c14_572x572.jpg?v=1615974779',
    description: "iPhone Official Leather Case. You can upgrade the system's memory to by installing a 260-pin SO-DIMM into the available slot to help increase the computer's efficiency when handling large projects. The system supports up to 64GB of RAM. A second M.2 slot is also available for additional storage. The integrated Intel UHD 630 graphics is designed to efficiently run a variety of applications with high detail. Up to three monitors can be connected across the computerâ¿¿s HDMI and DisplayPort outputs for enhanced viewing and multitasking efficiency.",
    status: 'In Stock',
  },
  {
    title: 'SAMSUNG GALAXY S11',
    price: 1499,
    category: 'Mobile Accessories',
    type: "Phone Casses",
    imgLink: 'https://cdn.shopify.com/s/files/1/1945/3873/products/c_608-m_437-299-1-5afa0a8d0f40d_560x560.jpg?v=1579496302',
    description: "SAMSUNG GALAXY S11 Black Marble Classic Case High quality Printing High quality and unique case hard cover for your phone Protects your Phone from scratches, dirt and bumps Precise openings on the case, allowing access to all controls and features of the Phone Made of durable material, shock Proof and deluxe.",
    status: 'In Stock',
  },


  {
    title: 'BASEUS M36 Power Bank',
    price: 5999,
    category: 'Mobile Accessories',
    type: "Power Banks",
    imgLink: 'https://cdn.shopify.com/s/files/1/1945/3873/products/Screen_Shot_2019-12-25_at_11.54.20_PM_677x675.png?v=1583923371',
    description: "BASEUS M36 WIRELESS CHARGER / POWER BANK - 10000MAH Baseus M36 Wireless Charger / Power Bank - 10000mAh - 5W, 2.1A - Dual USB Output - Li-poly Never run out of power with this Baseus M36 Wireless Charger/Power Bank. This portablecharge is packed with 10000mAh of battery capacity that allows you to charge up to 3devices at th same time: one wirelessly and two via USB port. One port has an output of 21A which enable you to charge larger devices like tablets while the other port is idealfor smartphones Maximum wireless charge power is 5W. Ultra-thin body and compact size areperfect for carryin it everywhere you go. Baseus M36 Wireless Charger/Power Bank isequipped with the lates security featuring overcharge, short circuit protection, automaticload detection, meta foreign body detection, so you never have to worry about your devicescharging. With LE indicator lamp, remaining charge is at a glance. It supports chargingwhile discharging.",
    status: 'In Stock',
  },
  {
    title: 'Baseus Power Bank',
    price: 4500,
    category: 'Mobile Accessories',
    type: "Power Banks",
    imgLink: 'https://cdn.shopify.com/s/files/1/1945/3873/products/14_46d9a4d6-9951-44ba-ba68-16290248843c_434x449.jpg?v=1613545112',
    description: "Baseus Power Bank 20000mAh 22.5W 3.0 Fast Charging PPXC-01 Warranty: Official Baseus 6 months replacement Policy by PhoneCase.pk (we are official Baseus Partners in Pakistan)",
    status: 'In Stock',
  },
  {
    title: 'Baseus Power Bank',
    price: 4500,
    category: 'Mobile Accessories',
    type: "Power Banks",
    imgLink: 'https://cdn.shopify.com/s/files/1/1945/3873/products/2_f65a6168-4066-475f-acdd-a302ec191b8c_400x399.jpg?v=1613542958',
    description: "Baseus 20000mAh Power Bank 18W PD 3.0 QC3.0 Fast Charging Supported PPALL-LG01 dirt and bumps Precise openings on the case, allowing access to all controls and features of the Phone Made of durable material, shock Proof and deluxe.",
    status: 'In Stock',
  },
  {
    title: 'Baseus Power Bank',
    price: 5500,
    category: 'Mobile Accessories',
    type: "Power Banks",
    imgLink: 'https://cdn.shopify.com/s/files/1/1945/3873/products/PrtScr_capture_226_933x933.jpg?v=1573030554',
    description: "30000 mAh Original Baseus Fast 3.0 Charger Power Bank PPJAN-C01 Warranty: Official Baseus 6 months replacement Policy by PhoneCase.pk (we are official Baseus Partners in Pakistan)",
    status: 'In Stock',
  },



  {
    title: 'L45 Type-C to Type-C & 3.5mm',
    price: 1599,
    category: 'Mobile Accessories',
    type: "Cables & Converters",
    imgLink: 'https://cdn.shopify.com/s/files/1/1945/3873/products/Baseus-CATL45-01-type-C-Male-to-type-C-Female-3-5.jpg_q50_1_9aa90f71-3af2-4a89-904b-79e1e4b545ce_1000x1000.jpg?v=1633598834',
    description: "Baseus L45 Type-C to Type-C And 3.5mm Jack Adapter & Converter. Warranty: Official Baseus 6 months replacement Policy by PhoneCase.pk (we are official Baseus Partners in Pakistan)",
    status: 'In Stock',
  },
  {
    title: 'USB To Type C OTG',
    price: 899,
    category: 'Mobile Accessories',
    type: "Cables & Converters",
    imgLink: 'https://cdn.shopify.com/s/files/1/1945/3873/products/9_58831fc3-ecf4-4fda-8936-721ad6cfd0bb_539x507.jpg?v=1604144165',
    description: "Baseus USB To Type C OTG Adapter USB USB-C Male To Micro USB Type-c Female Converter For Macbook & phone OTG Connector. Warranty: Official Baseus 6 months replacement Policy by PhoneCase.pk (we are official Baseus Partners in Pakistan)",
    status: 'In Stock',
  },
  {
    title: 'Rhythm Bent Connector 4 in 1',
    price: 1850,
    category: 'Mobile Accessories',
    type: "Cables & Converters",
    imgLink: 'https://cdn.shopify.com/s/files/1/1945/3873/products/2_d20a0198-e126-460a-a53e-37e399eb6585_993x993.jpg?v=1550656541',
    description: "Baseus Rhythm Bent Connector 4 in 1 Fast Charging+Audio+Call Function+1 Meter Cable for iPhone. Warranty: Official Baseus 6 months replacement Policy by PhoneCase.pk (we are official Baseus Partners in Pakistan)",
    status: 'In Stock',
  },
  {
    title: 'L54 Type-C to 3.5mm earphone headphone',
    price: 899,
    category: 'Mobile Accessories',
    type: "Cables & Converters",
    imgLink: 'https://cdn.shopify.com/s/files/1/1945/3873/products/19_ea75eed4-36e6-4ab6-98ef-2f4ae490a0cf_1000x1000.jpg?v=1594207660',
    description: "Baseus L54 Type c to 3.5mm earphone headphone adapter usb c to 3.5 jack audio Earphone Cable Adapter. Warranty: Official Baseus 6 months replacement Policy by PhoneCase.pk (we are official Baseus Partners in Pakistan)",
    status: 'In Stock',
  },



  {
    title: 'Native Union Wireless Charger',
    price: 80999,
    category: 'Mobile Accessories',
    type: "Wireless Chargers",
    imgLink: 'https://media.wired.com/photos/5fd9437b56969d5ef484f36f/master/w_960%2Cc_limit/Gear-Native-Union-Dock-SOURCE-Native-Union.jpg',
    description: "This is one of the prettiest wireless chargers I've tested, especially in the rose color. The large circular fabric looks nice (and won't scratch your phone), plus the steel base and silicone grips prevent it from wobbling or sliding around. I really like that the LED is on the back. In a dark room, it emits a very faint glow, enough to make sure it's charging but not so distracting I had trouble sleeping. That's something I can't say for the many other wireless chargers with blazing lights on the front. You can charge in landscape or portrait orientation. The downside? No power adapter is included, but you get a 6.5-foot-long USB-A to USB-C cable.",
    status: 'In Stock',
  },
  {
    title: 'Nomad Base Station Mini',
    price: 50999,
    category: 'Mobile Accessories',
    type: "Wireless Chargers",
    imgLink: 'https://media.wired.com/photos/61083994c158eb9a50b443ba/master/w_960%2Cc_limit/gear_chargers_nomad.jpg',
    description: "This little charger from Nomad is tied for looks with our top pick. I love the padded black leather surface, which looks elegant when paired with the aluminum chassis. It's fairly hefty, too, so it doesn't slide around a desk. (The rubber feet help.) The LED isn't too obtrusive, and it dims if there's little to no light in the room. You get a USB-C to USB-C cable in the box, so you can plug it into your Android phone directly if you need to charge it faster. There's no power adapter, though, and you'll need to use a 30-watt adapter to hit 15-watt speeds with an Android phone.",
    status: 'In Stock',
  },
  {
    title: 'Anker PowerWave Pad & Stand',
    price: 2499,
    category: 'Mobile Accessories',
    type: "Wireless Chargers",
    imgLink: 'https://media.wired.com/photos/5dc5b461dea30b00096c6ca8/master/w_960%2Cc_limit/Gear-anker-wireless-charging-stand.jpg',
    description: "Anker's pad and stand prove you don't need to spend much for wireless charging. They're both made from plastic with a rubbery finish on the bottom to prevent slips and slides, though it's not too grippy. A tiny LED lights up blue when it’s charging and flashes to indicate there’s a problem. We prefer stands over pads, because you can easily see your phone notifications, but Anker's pad is so cheap you could grab a few to scatter around your home. Both come with a 4-foot Micro USB cable, but you have to supply your own power adapter. That’s not a big surprise at this price. Most importantly, they'll charge your phone every bit as capably as the other options in our guide.",
    status: 'In Stock',
  },


  // Laptops 
  {
    title: 'Dell Vostro 3500',
    price: 79599,
    category: 'Laptops',
    type: "Dell Laptop",
    imgLink: 'https://www.czone.com.pk/images/products/copy-copy-copy-copy-dv3500nt-cnb-00060lb055-bk-1540-11095-190221120323.jpg',
    description: 'Dell Vostro 3500 Laptop 11th Gen Intel Core i3 4GB 1TB Intel Graphics 15.6" HD | Accent Black 15.6-inch laptop featuring a 2-sided narrow border, ExpressCharge™ battery, and 11th Gen Intel® Core™ processors.',
    status: 'In Stock',
  },
  {
    title: 'Dell Inspiron 3501',
    price: 2499,
    category: 'Laptops',
    type: "Dell Laptop",
    imgLink: 'https://www.czone.com.pk/images/products/3-czone.com.pk-1540-12023-310821123412.jpg',
    description: 'Dell Inspiron 3501 Laptop 11Th Gen Intel Core i3, 4GB, 1TB HDD, Intel Graphics, 15.6" FHD | Quarry Blue (Official Warranty) 38.1cm (15) laptop featuring responsive performance in a sleek design with 2-sided narrow borders, optional PCIe SSDs, Express Charge*, and Intel Core processors.',
    status: 'In Stock',
  },
  {
    title: 'Dell Vostro 3500',
    price: 80499,
    category: 'Laptops',
    type: "Dell Laptop",
    imgLink: 'https://www.czone.com.pk/images/products/copy-copy-copy-copy-dv3500nt-cnb-05000ff090-bk-1540-11095-190221120320.jpg',
    description: 'Dell Vostro 3500 Laptop 11th Gen Intel Core i3, 4GB, 1TB HDD, Intel Graphics, 15.6" FHD, Dell Essential Backpack | Accent Black (Official Warranty), ExpressCharge™ battery, and 11th Gen Intel® Core™ processors.',
    status: 'In Stock',
  },
 
  {
    title: 'HP 14-DK1005NIA',
    price: 63999,
    category: 'Laptops',
    type: "HP Laptop",
    imgLink: 'https://www.czone.com.pk/images/products/14-czone.com.pk-1540-12040-020921055033.jpg',
    description: 'HP 14-DK1005NIA Laptop AMD Athlon Silver 3050U, 4GB, 1TB HDD, 14" HD Get reliable performance on the go with the HP 14-DK1005NIA Laptop. With long battery life, you can stay social, productive, and connected.',
    status: 'In Stock',
  },
  {
    title: 'HP 15-DW3024NIA',
    price: 85599,
    category: 'Laptops',
    type: "HP Laptop",
    imgLink: 'https://www.czone.com.pk/images/products/71p-urytwjl.-sl1500--4012-600721-010321035040-1540-11191-080321071112.jpg',
    description: 'HP 15-DW3024NIA Laptop - 11th Gen Intel Core i3, 4GB, 256GB SSD, Jet black Stay connected to what matters most with long-lasting battery life and a sleek and portable, micro-edge bezel design. Built to keep you productive and entertained from anywhere, the HP 15" laptop features reliable performance and an expansive display - letting you stream, surf and speed through tasks from sun up to sundown.',
    status: 'In Stock',
  },
  {
    title: 'HP 15-DW3033dx',
    price: 86099,
    category: 'Laptops',
    type: "HP Laptop",
    imgLink: 'https://www.czone.com.pk/images/products/1-czone.com.pk-1540-11972-210821100550.jpg',
    description: 'HP 15-DW3033dx Laptop 11th Gen Intel Core i3, 8GB, 256GB SSD, Intel Graphics, Windows 10 - 15.6" diagonal, FHD (1920 x 1080), IPS, micro-edge, anti-glare, 250 nits, 45% NTSC.',
    status: 'In Stock',
  },


  {
    title: 'Lenovo Ideapad 330',
    price: 56500,
    category: 'Laptops',
    type: "Lenovo Laptop",
    imgLink: 'https://www.czone.com.pk/images/products/34-850-876-v25-2-1540-11319-260321072511.jpg',
    description: 'Lenovo Ideapad 330 Laptop - Intel Celeron N4000, 4GB, 1TB, Platinum Grey (Local Warranty). A laptop isn’t just a piece of electronics—it’s also an investment. That’s why we designed the Ideapad 330 with a special protective finish to guard against wear and tear, as well as rubber detailing on the bottom to maximize ventilation and extend component life.',
    status: 'In Stock',
  },
  {
    title: 'Lenovo IdeaPad 3',
    price: 65500,
    category: 'Laptops',
    type: "Lenovo Laptop",
    imgLink: 'https://www.czone.com.pk/images/products/23-czone.com.pk-1540-11062-150221101020.jpg',
    description: 'Lenovo IdeaPad 3 Laptop - Intel Pentium Gold 6405U, 4GB, 128GB SSD, Business Black, W10. The IdeaPad 3 is priced as an everyday-use laptop—but engineered as something much more. 10th Gen Intel® Core™ processing—as well as powerful memory and storage options—means this PC delivers beyond expectations. 81wa00b1us.',
    status: 'In Stock',
  },
  {
    title: 'Lenovo IdeaPad 5',
    price: 114500,
    category: 'Laptops',
    type: "Lenovo Laptop",
    imgLink: 'https://www.czone.com.pk/images/products/1-czone.com.pk-1540-11823-290621100401.jpg',
    description: 'Lenovo IdeaPad 5 Laptop 11th Gen Intel Core i5, 8GB, 512GB SSD, Intel Graphics, Backlit KB, 15.6" FHD IPS, Graphite Grey (Official Warranty). The IdeaPad 5 15" boasts an enticing list of standard and optional features, so you can make it as streamlined or powerful as you want without breaking the bank.',
    status: 'In Stock',
  },
  {
    title: 'Lenovo ThinkBook 15 G2',
    price: 125900,
    category: 'Laptops',
    type: "Lenovo Laptop",
    imgLink: 'https://www.czone.com.pk/images/products/copy-copy-copy-14-czone.com.pk-1540-11944-100821114037.jpg',
    description: 'Lenovo ThinkBook 15 G2 Laptop 11th Gen Intel Core i5, 8GB. 1TB HDD, MX450 2GB, 15.6" FHD | Mineral Grey. Enjoy a heavy-duty performance on the Lenovo ThinkBook 15 Gen 2 (15" Intel) laptop, thanks to advanced 11th Gen Intel® Core™ processors enhanced by AI technology.',
    status: 'In Stock',
  },


  // Furniture
  {
    title: 'bed side table',
    price: 2500,
    category: 'Furniture',
    type: "Bedroom",
    imgLink: 'https://pk-live-21.slatic.net/kf/S7827408d1c3e4d2d9599fc6e4a51b2b0C.jpg',
    description: 'bed side table heavy-duty performance on the Lenovo ThinkBook 15 Gen 2 (15" Intel) laptop, thanks to advanced 11th Gen Intel® Core™ processors enhanced by AI technology.',
    status: 'In Stock',
  },
  {
    title: 'Bed Set 103',
    price: 120900,
    category: 'Furniture',
    type: "Bedroom",
    imgLink: 'https://www.malikfurniture.pk/wp-content/uploads/2019/04/bed-1-104.jpg',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    status: 'In Stock',
  },
  {
    title: 'Bed Set 115',
    price: 185900,
    category: 'Furniture',
    type: "Bedroom",
    imgLink: 'https://www.malikfurniture.pk/wp-content/uploads/2019/09/bed-1-115.jpg',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    status: 'In Stock',
  },


  {
    title: 'Seven Warrior Gaming Desk',
    price: 185900,
    category: 'Furniture',
    type: "Gaming Furniture",
    imgLink: 'https://m.media-amazon.com/images/I/71H5+X1G2CL._AC_SX569_.jpg',
    description: 'Seven Warrior Gaming Desk 47INCH with Dual Monitor Mount, Carbon Fiber Surface Computer Gamer Desk with Full Desk Mouse Pad, Ergonomic Y Shaped Gamer Table with Outlet Organizer, Gaming Rack Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    status: 'In Stock',
  },
 
  {
    title: 'Atlantic Gaming Gaming-Desk',
    price: 18900,
    category: 'Furniture',
    type: "Gaming Furniture",
    imgLink: 'https://m.media-amazon.com/images/I/81jkudzDh2L._AC_SL1500_.jpg',
    description: 'Atlantic Gaming Original Gaming-Desk Pro - Curved-Front, 10 Games, Controller, Headphone & Speaker Storage, 40.25x23.5 inch Curved Front Desktop, Enhanced Larger Design, Black, 33950212 Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    status: 'In Stock',
  },
  {
    title: 'DXRacer Racing Simulator Gaming Chair',
    price: 18900,
    category: 'Furniture',
    type: "Gaming Furniture",
    imgLink: 'http://www.gtstore.pk/products/large3082-11718002757.jpg',
    description: 'DXRacer Racing Simulator Gaming Chair part-3 Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    status: 'In Stock',
  },


  {
    title: 'Selene',
    price: 55700,
    category: 'Furniture',
    type: "Home Office",
    imgLink: 'https://cdn.shopify.com/s/files/1/0513/7858/5789/products/28-1200-px-x-1840-px-fro_1024x1024@2x.jpg?v=1617273349',
    description: 'Master Offisys Selene is known for its streamlined structure and clean lines. The minimalistic design of the table draws inspiration from minimalism. The veneer base of the table balances the melamine finished tabletop effortlessly offering an ergonomic working experience.',
    status: 'In Stock',
  },
  {
    title: 'Executive Desk (MO-ED-ES-25)',
    price: 55700,
    category: 'Furniture',
    type: "Home Office",
    imgLink: 'https://cdn.shopify.com/s/files/1/0513/7858/5789/products/43-1200-px-x-1840-px-fro_1024x1024@2x.jpg?v=1617273192',
    description: 'Sophisticated, polished and ergonomic are some of the synonyms of MO-ED-ED-25. It s sleek design and unique shape makes it amongst the best!',
    status: 'In Stock',
  },
  {
    title: 'Acute',
    price: 55700,
    category: 'Furniture',
    type: "Home Office",
    imgLink: 'https://cdn.shopify.com/s/files/1/0513/7858/5789/products/50-1200-px-x-1840-px-fro_1080x.jpg?v=1621865992',
    description: 'This contemporary L-shaped Executive table is bound to deliver a classic personality to your opulent offices. With a rich veneer finish, the subtle and functional design of this expertly crafted furniture piece brings an authoritative aura to the overall personality of your office. The product is buffed with atoxic material to maintain air quality for a healthier working experience.',
    status: 'In Stock',
  },
 

  // Kitchen & Dining
  {
    title: 'Coffee Beater & Mixer',
    price: 55700,
    category: 'Kitchen & Dining',
    type: "Coffee & Tea",
    imgLink: 'https://static-01.daraz.pk/p/b6d4d01b31bdce14d17719c135582e08.jpg',
    description: 'This contemporary L-shaped Executive table is bound to deliver a classic personality to your opulent offices. With a rich veneer finish, the subtle and functional design of this expertly crafted furniture piece brings an authoritative aura to the overall personality of your office. The product is buffed with atoxic material to maintain air quality for a healthier working experience.',
    status: 'In Stock',
  },
  {
    title: 'Thermocup Electric Cattle',
    price: 55700,
    category: 'Kitchen & Dining',
    type: "Coffee & Tea",
    imgLink: 'https://static-01.daraz.pk/p/03eeb73cf93f6a0ae85a6952d4a4b8fd.jpg',
    description: 'This contemporary L-shaped Executive table is bound to deliver a classic personality to your opulent offices. With a rich veneer finish, the subtle and functional design of this expertly crafted furniture piece brings an authoritative aura to the overall personality of your office. The product is buffed with atoxic material to maintain air quality for a healthier working experience.',
    status: 'In Stock',
  },
  {
    title: 'Electric Coffee Beater',
    price: 55700,
    category: 'Kitchen & Dining',
    type: "Coffee & Tea",
    imgLink: 'https://static-01.daraz.pk/p/5d305ae6f709c455f39b56631b97c829.jpg',
    description: 'This contemporary L-shaped Executive table is bound to deliver a classic personality to your opulent offices. With a rich veneer finish, the subtle and functional design of this expertly crafted furniture piece brings an authoritative aura to the overall personality of your office. The product is buffed with atoxic material to maintain air quality for a healthier working experience.',
    status: 'In Stock',
  },


  {
    title: 'Fridge Cover With Pockets',
    price: 490,
    category: 'Kitchen & Dining',
    type: "Kitchen & Table linen",
    imgLink: 'https://static-01.daraz.pk/p/a4ad9b855d0f09f26668db5d47040a61.jpg',
    description: 'Anti-dust Waterproof Oil-proof Refrigerator Fridge Cover With 6 Pockets Organzier. This contemporary L-shaped Executive table is bound to deliver a classic personality to your opulent offices. With a rich veneer finish, the subtle and functional design of this expertly crafted furniture piece brings an authoritative aura to the overall personality of your office. The product is buffed with atoxic material to maintain air quality for a healthier working experience.',
    status: 'In Stock',
  },
  {
    title: 'Silicone Heat Resistant Gloves',
    price: 550,
    category: 'Kitchen & Dining',
    type: "Kitchen & Table linen",
    imgLink: 'https://static-01.daraz.pk/p/488d652e72eae5c8c10184169bb68f8d.jpg',
    description: 'Anti-dust Waterproof Oil-proof Refrigerator Fridge Cover With 6 Pockets Organzier. This contemporary L-shaped Executive table is bound to deliver a classic personality to your opulent offices. With a rich veneer finish, the subtle and functional design of this expertly crafted furniture piece brings an authoritative aura to the overall personality of your office. The product is buffed with atoxic material to maintain air quality for a healthier working experience.',
    status: 'In Stock',
  },
  {
    title: 'Waterproof Printed Table Sheet',
    price: 169,
    category: 'Kitchen & Dining',
    type: "Kitchen & Table linen",
    imgLink: 'https://static-01.daraz.pk/p/94e042f95ee45491b74aed31aafeb1ad.png',
    description: 'Anti-dust Waterproof Oil-proof Refrigerator Fridge Cover With 6 Pockets Organzier. This contemporary L-shaped Executive table is bound to deliver a classic personality to your opulent offices. With a rich veneer finish, the subtle and functional design of this expertly crafted furniture piece brings an authoritative aura to the overall personality of your office. The product is buffed with atoxic material to maintain air quality for a healthier working experience.',
    status: 'In Stock',
  },


  {
    title: 'FRAKIN Manual Egg Beater',
    price: 169,
    category: 'Kitchen & Dining',
    type: "Kitchen Utensils",
    imgLink: 'https://static-01.daraz.pk/p/f56720cbce850c8fde65dea1ccb8eed2.jpg',
    description: 'Anti-dust Waterproof Oil-proof Refrigerator Fridge Cover With 6 Pockets Organzier. This contemporary L-shaped Executive table is bound to deliver a classic personality to your opulent offices. With a rich veneer finish, the subtle and functional design of this expertly crafted furniture piece brings an authoritative aura to the overall personality of your office. The product is buffed with atoxic material to maintain air quality for a healthier working experience.',
    status: 'In Stock',
  },
  {
    title: 'Silicone Spoon Heat Resistant',
    price: 169,
    category: 'Kitchen & Dining',
    type: "Kitchen Utensils",
    imgLink: 'https://static-01.daraz.pk/p/c4232594e9a94e3f86b8122c3a4d3e62.jpg',
    description: 'Silicone Spoon Rest Heat Resistant . This contemporary L-shaped Executive table is bound to deliver a classic personality to your opulent offices. With a rich veneer finish, the subtle and functional design of this expertly crafted furniture piece brings an authoritative aura to the overall personality of your office. The product is buffed with atoxic material to maintain air quality for a healthier working experience.',
    status: 'In Stock',
  },
  {
    title: 'Non Stick Cooking Spoon Set',
    price: 169,
    category: 'Kitchen & Dining',
    type: "Kitchen Utensils",
    imgLink: 'https://static-01.daraz.pk/p/4e771a1ee04d5c27e8a308c2b5e2c75c.jpg_340x340q80.jpg_.webp',
    description: 'Anti-dust Waterproof Oil-proof Refrigerator Fridge Cover With 6 Pockets Organzier. This contemporary L-shaped Executive table is bound to deliver a classic personality to your opulent offices. With a rich veneer finish, the subtle and functional design of this expertly crafted furniture piece brings an authoritative aura to the overall personality of your office. The product is buffed with atoxic material to maintain air quality for a healthier working experience.',
    status: 'In Stock',
  },
  {
    title: 'Cutlery Organizer.ZA17-226',
    price: 169,
    category: 'Kitchen & Dining',
    type: "Kitchen Utensils",
    imgLink: 'https://cdn.shopify.com/s/files/1/0429/7654/2881/products/KITB40AAA211000_2_df90b76b-6d23-4e44-be71-2f32ccb5a8e1.jpg?v=1634903769',
    description: 'Organize your cutlery with our unique designed Compact Cutlery organizer. It contains 4 stacked compartments for easy cutlery identification. With a rich veneer finish, the subtle and functional design of this expertly crafted furniture piece brings an authoritative aura to the overall personality of your office. The product is buffed with atoxic material to maintain air quality for a healthier working experience.',
    status: 'In Stock',
  },
 

]


export default cardData





